# Generated by Django 4.2.14 on 2024-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynewmodel',
            name='tip',
            field=models.CharField(choices=[(None, 'Выберите тип'), ('b', 'er'), ('s', 'ter'), ('c', 'ber')], default='s', max_length=1),
        ),
    ]
